services:
  nobet_app:
    image: ghcr.io/treabet/nobetmatik:latest
    restart: unless-stopped
    labels:
      # TRAEFIK YÖNLENDİRME (Routing)
      - "traefik.enable=true"
      - "traefik.http.routers.nobet.rule=Host(`nobet.treabethome.shop`)"
      - "traefik.http.routers.nobet.entrypoints=https"
      - "traefik.http.routers.nobet.tls=true"
      - "traefik.http.routers.nobet.tls.certresolver=cloudflare"
      - "traefik.http.services.nobet.loadbalancer.server.port=80"

    networks:
      - proxy

networks:
  proxy:
    external: true
